### ISSUE TITLE
Don't use brackets in a return statement?

### ISSUE THREAD

**Issue by alexbirkett** [bakkenbaeck/android-playbook#4]
Does this mean "Don't wrap return statements in braces"? 

Would this be acceptable?

```java
   private static int calculate(int x, int y, int z) {
        return (x + y) * z;
    }
```

**Comment by alexbirkett** [comment]
Ignore the fact that `x`, `y` and `z` are not acceptable variable names ;)

**Comment by alexbirkett** [comment]
Not sure if "brackets" is the correct terminology either? https://www.cis.upenn.edu/~matuszek/General/JavaSyntax/parentheses.html

**Comment by csdodd** [comment]
`return (x + y) * z;` is _technically_ fine.

Though since we have a preference for named arguments this would possibly be better.

```
private static int calculate(int x, int y, int z) {
    final int w = (x + y) * z;
    return w;
}
``` 

Back to the original point though. "Don't wrap statements in braces" - don't do this:

`return (x + y);`

I'll give an example and change "braces" to "parentheses"
